In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris

In [5]:
iris = load_iris()
dataset = pd.DataFrame(iris.data, columns = iris.feature_names)
print(dataset.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2


In [6]:
dataset['target'] = iris.target

In [7]:
print(dataset['target'])

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32


In [8]:
x_train , x_test , y_train , y_test = train_test_split(np.array(dataset)[:,:4], np.array(dataset)[:,4], random_state=50, test_size = 0.25)

In [9]:
print(y_train[0])

1.0


In [10]:
import tensorflow as tf

y_train = tf.keras.utils.to_categorical(y_train-1, num_classes=3)
print(y_train)
y_test = tf.keras.utils.to_categorical(y_test-1, num_classes=3)
print(y_test)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0.

In [11]:
y_train[0]

array([1., 0., 0.], dtype=float32)

In [12]:
from keras.models import Sequential
from keras.layers import Dense

# define the keras model
model = Sequential()
model.add(Dense(12,  input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(3, activation='softmax'))

sgd = tf.keras.optimizers.SGD(learning_rate=0.001, momentum=0.9, nesterov=True)

#adam = keras.optimizers.Adam(learning_rate=0.01)

# compile the keras model
model.compile(loss='categorical_crossentropy', optimizer= sgd, metrics=['accuracy'])

In [13]:
history = model.fit(x_train, y_train, epochs=28, batch_size=15)

# evaluate the keras model
_, accuracy = model.evaluate(x_test, y_test)
print('Accuracy: %.2f' % (accuracy*100))

Epoch 1/28
8/8 [==============================] - 1s 6ms/step - loss: 1.2505 - accuracy: 0.5893
Epoch 2/28
8/8 [==============================] - 0s 4ms/step - loss: 1.1199 - accuracy: 0.3482
Epoch 3/28
8/8 [==============================] - 0s 3ms/step - loss: 1.0864 - accuracy: 0.4375
Epoch 4/28
8/8 [==============================] - 0s 4ms/step - loss: 1.0284 - accuracy: 0.4643
Epoch 5/28
8/8 [==============================] - 0s 4ms/step - loss: 0.9932 - accuracy: 0.4286
Epoch 6/28
8/8 [==============================] - 0s 4ms/step - loss: 0.9710 - accuracy: 0.6518
Epoch 7/28
8/8 [==============================] - 0s 4ms/step - loss: 0.9521 - accuracy: 0.6786
Epoch 8/28
8/8 [==============================] - 0s 5ms/step - loss: 0.9347 - accuracy: 0.7054
Epoch 9/28
8/8 [==============================] - 0s 5ms/step - loss: 0.9163 - accuracy: 0.7321
Epoch 10/28
8/8 [==============================] - 0s 5ms/step - loss: 0.8887 - accuracy: 0.8393
Epoch 11/28
8/8 [======================